[package]
name = "builder-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
synapsed-builder = { path = "../../tools/builder" }
tokio = { version = "1.41", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"